# Slicing arrays

In [16]:
import numpy as np
arr0=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr0[0:5])
print(arr0[4:])
print(arr0[-3:-1])
print(arr0[0:5:2])
print(arr0[::2])

[1 2 3 4 5]
[ 5  6  7  8  9 10]
[8 9]
[1 3 5]
[1 3 5 7 9]


# Slicing 2-D Arrays

In [20]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1,1:4])

[7 8 9]


In [27]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0,1:5])
print(arr[0,::])

[2 3 4 5]
[1 2 3 4 5]


In [32]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2,0:2])
print(arr[0:2,1:4])

[[1 2]
 [6 7]]
[[2 3 4]
 [7 8 9]]


# Access 3-D Arrays

In [40]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0:2,0,0:3])

[[1 2 3]
 [7 8 9]]
