# NumPy Creating Arrays

In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [15]:
tuples=np.array((1,2,3,4,5))
print(tuples)
print(tuples.ndim)

[1 2 3 4 5]
1


In [14]:
array=np.array(5)
print(array)
print(array.ndim)

5
0


In [13]:
arr=np.array([1,2])
print(arr)
print(arr.ndim)

[1 2]
1


In [12]:
arr=np.array([[1,2],[3,4]])
print(arr)
print(arr.ndim)

[[1 2]
 [3 4]]
2


In [11]:
arr1=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[8,10],[11,12]]])
print(arr1)
print(arr1.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 8 10]
  [11 12]]]
3


In [19]:
arr0=np.array([1,2,3,4,5],ndmin=8)
print(arr0)
print(arr0.ndim)

[[[[[[[[1 2 3 4 5]]]]]]]]
8
