In [3]:
import numpy as np
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
a=v1+v2
b=v1-v2
c=v1@v2
e=np.cross(v1,v2)
d=np.linalg.norm(v1)
print("\n" ,a,"\n", b,"\n" ,c,"\n",d,"\n",e)
print(v1[1])



 [5 7 9] 
 [-3 -3 -3] 
 32 
 3.7416573867739413 
 [-3  6 -3]
2


In [43]:
m1 = np.array([[1, 2] ,[3, 4]])
m2 = np.array([[5, 6],[7, 8]])
k=(m1+m2)
z=m1-m2
l=m1@m2
n=m1.T
n=m2.T
s=np.linalg.det(m1)
print("\n",k,"\n",z,"\n",l,"\n",n,"\n",s)


 [[ 6  8]
 [10 12]] 
 [[-4 -4]
 [-4 -4]] 
 [[19 22]
 [43 50]] 
 [[5 7]
 [6 8]] 
 -2.0000000000000004


In [11]:

v1= np.array([1, 2, 3])
v= 2.5
def scale_vector(v1, v):
    result=v1*v
    return result 
print(scale_vector(v1, v))

[2.5 5.  7.5]


In [3]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
a=np.dot(v1,v2)
print(a)
b=np.linalg.norm(v1)
c=np.linalg.norm(v2)
d=a/(b*c)
e=np.arccos(d)
print(e)

32
0.2257261285527342


In [15]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
g=np.dot(v1,v2)
print(a)
h=np.linalg.norm(v2)**2
print(f'{h:.0f}')
pro=(g/h)*v2
print(np.round(pro, 2))

32
77
[1.66 2.08 2.49]


In [20]:
v1=np.array([1,0])
degree=90
rad=np.radians(degree)
#R = np.array([[cosθ, -sinθ],[sinθ, cosθ]])
c=np.cos(rad)
s=np.sin(rad)
# 2. Build the Rotation Matrix R
# R = [[cosθ, -sinθ], [sinθ, cosθ]]
R = np.array([[c, -s],
              [s,  c]])

# 3. Rotate the vector using the @ operator (Matrix Multiplication)
v_rotated = R @ v1

print(f"Original Vector: {v1}")
print(f"Rotation Matrix:\n{np.round(R,1)}")
print(f"Rotated Vector: {np.round(v_rotated,1)}")


Original Vector: [1 0]
Rotation Matrix:
[[ 0. -1.]
 [ 1.  0.]]
Rotated Vector: [0. 1.]


In [19]:
A = [[ 2, -1], [-1, 2]]
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print()
print(eigenvectors)
#VERIFICATION
#AV= λv 
print()
AV=np.dot(A,eigenvectors)
print(AV)
print()
λv=eigenvalues* eigenvectors
print(λv)

[3. 1.]

[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]

[[ 2.12132034  0.70710678]
 [-2.12132034  0.70710678]]

[[ 2.12132034  0.70710678]
 [-2.12132034  0.70710678]]
